// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice =
  | WhoWeAreSlice
  | WhyChooseUsSlice
  | OurValueSlice
  | OurTeamSlice
  | ReviewsSlice
  | MapSlice
  | CallToActionSlice
  | TestimonialsSlice
  | ContentGridSlice
  | HighlightSlice
  | BlogGridSlice
  | HeroSlice
  | VideoBannerSlice
  | GetInTouchBlockSlice
  | BlogPreviewSlice
  | PostSlice
  | BodySlice
  | BannerSlice;

/**
 * Content for Post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Banner field in *Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: blog_post.banner
   * - **Tab**: Banner
   * - **Documentation**: https://prismic.io/docs/field#select
   */;
  banner: prismic.SelectField<"Default" | "Text Bottom", "filled"> /**
   * Add To Menu field in *Post*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_post.add_to_menu
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */;
  add_to_menu: prismic.BooleanField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type LocationDocumentDataSlicesSlice = BodySlice;

/**
 * Content for Location documents
 */
interface LocationDocumentData {
  /**
   * Location field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Slice Zone field in *Location*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: location.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LocationDocumentDataSlicesSlice> /**
   * Meta Description field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: location.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Location*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: location.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: location.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Location document from Prismic
 *
 * - **API ID**: `location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LocationDocumentData>,
    "location",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | WhyChooseUsSlice
  | WhoWeAreSlice
  | OurValueSlice
  | OurTeamSlice
  | ReviewsSlice
  | MapSlice
  | CallToActionSlice
  | PostSlice
  | VideoBannerSlice
  | BlogPreviewSlice
  | TestimonialsSlice
  | GetInTouchBlockSlice
  | BlogGridSlice
  | ContentGridSlice
  | BodySlice
  | BannerSlice
  | HeroSlice
  | HighlightSlice;

/**
 * Item in *Page → DropDown Items*
 */
export interface PageDocumentDataDropdownItemsItem {
  /**
   * link field in *Page → DropDown Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.dropdown_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"page" | "blog_post" | "service_page">;
}

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Add To Menu field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.add_to_menu
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */;
  add_to_menu: prismic.BooleanField;

  /**
   * IsDropDown field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.isdropdown
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isdropdown: prismic.BooleanField;

  /**
   * Act As Button (AAB) field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.act_as_button
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  act_as_button: prismic.BooleanField;

  /**
   * Button Trigger (requires AAB) field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.button_trigger
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_trigger: prismic.KeyTextField;

  /**
   * DropDown Items field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.dropdown_items[]
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  dropdown_items: prismic.GroupField<
    Simplify<PageDocumentDataDropdownItemsItem>
  >;

  /**
   * Index field in *Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: page.index
   * - **Tab**: Menu Settings
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  index: prismic.NumberField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServicePageDocumentDataSlicesSlice =
  | WhoWeAreSlice
  | WhyChooseUsSlice
  | OurTeamSlice
  | OurValueSlice
  | ReviewsSlice
  | MapSlice
  | CallToActionSlice
  | BlogGridSlice
  | HighlightSlice
  | PostSlice
  | HeroSlice
  | VideoBannerSlice
  | GetInTouchBlockSlice
  | BlogPreviewSlice
  | TestimonialsSlice
  | ContentGridSlice
  | BodySlice
  | BannerSlice;

/**
 * Content for Service documents
 */
interface ServicePageDocumentData {
  /**
   * Title field in *Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicePageDocumentData>,
    "service_page",
    Lang
  >;

type SettingsDocumentDataSlicesSlice = never;

/**
 * Item in *Settings → CTA*
 */
export interface SettingsDocumentDataCtaItem {
  /**
   * Icon field in *Settings → CTA*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Label field in *Settings → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Menu*
 */
export interface SettingsDocumentDataMenuItem {
  /**
   * link field in *Settings → Menu*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<"page">;
}

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Icon field in *Settings → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<
    "Facebook" | "Instagram" | "Linkedin" | "Twitter" | "Youtube"
  >;

  /**
   * link field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice> /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  logo: prismic.ImageField<never>;

  /**
   * CTA field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta: prismic.GroupField<Simplify<SettingsDocumentDataCtaItem>> /**
   * Newsletter Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  newsletter_text: prismic.RichTextField;

  /**
   * Menu field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.menu[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu: prismic.GroupField<Simplify<SettingsDocumentDataMenuItem>> /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  > /**
   * Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  address: prismic.KeyTextField;

  /**
   * Phone field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.phone
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Store Hours field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.store_hours
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  store_hours: prismic.KeyTextField;

  /**
   * Calendly link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.calendly_link
   * - **Tab**: Contact
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  calendly_link: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | LocationDocument
  | PageDocument
  | ServicePageDocument
  | SettingsDocument;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Heading field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Background Image field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceTextBottomPrimary {
  /**
   * Tagline field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Background Image field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Text Bottom variation for Banner Slice
 *
 * - **API ID**: `textBottom`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceTextBottom = prismic.SharedSliceVariation<
  "textBottom",
  Simplify<BannerSliceTextBottomPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault | BannerSliceTextBottom;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BlogGrid → Primary*
 */
export interface BlogGridSliceDefaultPrimary {
  /**
   * Posts Count field in *BlogGrid → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_grid.primary.posts_count
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  posts_count: prismic.NumberField;

  /**
   * Direction field in *BlogGrid → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog_grid.primary.is_ascending
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_ascending: prismic.BooleanField;
}

/**
 * Default variation for BlogGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogGrid*
 */
type BlogGridSliceVariation = BlogGridSliceDefault;

/**
 * BlogGrid Shared Slice
 *
 * - **API ID**: `blog_grid`
 * - **Description**: BlogGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogGridSlice = prismic.SharedSlice<
  "blog_grid",
  BlogGridSliceVariation
>;

/**
 * Primary content in *BlogPreview → Primary*
 */
export interface BlogPreviewSliceDefaultPrimary {
  /**
   * Image field in *BlogPreview → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *BlogPreview → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *BlogPreview → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *BlogPreview → Items*
 */
export interface BlogPreviewSliceDefaultItem {
  /**
   * post field in *BlogPreview → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview.items[].post
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  post: prismic.ContentRelationshipField<"blog_post">;
}

/**
 * Default variation for BlogPreview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPreviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPreviewSliceDefaultPrimary>,
  Simplify<BlogPreviewSliceDefaultItem>
>;

/**
 * Slice variation for *BlogPreview*
 */
type BlogPreviewSliceVariation = BlogPreviewSliceDefault;

/**
 * BlogPreview Shared Slice
 *
 * - **API ID**: `blog_preview`
 * - **Description**: BlogPreview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPreviewSlice = prismic.SharedSlice<
  "blog_preview",
  BlogPreviewSliceVariation
>;

/**
 * Primary content in *Body → Primary*
 */
export interface BodySliceDefaultPrimary {
  /**
   * Body field in *Body → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: body.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Body Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BodySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BodySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Body*
 */
type BodySliceVariation = BodySliceDefault;

/**
 * Body Shared Slice
 *
 * - **API ID**: `body`
 * - **Description**: Body
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BodySlice = prismic.SharedSlice<"body", BodySliceVariation>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Tagline field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Button Label field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Trigger field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.button_trigger
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_trigger: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContentGrid → Primary*
 */
export interface ContentGridSliceDefaultPrimary {
  /**
   * Heading field in *ContentGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *ContentGrid → Items*
 */
export interface ContentGridSliceDefaultItem {
  /**
   * card field in *ContentGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_grid.items[].card
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card: prismic.ContentRelationshipField;
}

/**
 * Default variation for ContentGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentGridSliceDefaultPrimary>,
  Simplify<ContentGridSliceDefaultItem>
>;

/**
 * Slice variation for *ContentGrid*
 */
type ContentGridSliceVariation = ContentGridSliceDefault;

/**
 * ContentGrid Shared Slice
 *
 * - **API ID**: `content_grid`
 * - **Description**: ContentGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentGridSlice = prismic.SharedSlice<
  "content_grid",
  ContentGridSliceVariation
>;

/**
 * Primary content in *FaqSection → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Heading field in *FaqSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *FaqSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *FaqSection → Items*
 */
export interface FaqSectionSliceDefaultItem {
  /**
   * Trigger field in *FaqSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].trigger
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  trigger: prismic.KeyTextField;

  /**
   * Content field in *FaqSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.items[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  Simplify<FaqSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Default variation for GetInTouchBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetInTouchBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *GetInTouchBlock*
 */
type GetInTouchBlockSliceVariation = GetInTouchBlockSliceDefault;

/**
 * GetInTouchBlock Shared Slice
 *
 * - **API ID**: `get_in_touch_block`
 * - **Description**: GetInTouchBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetInTouchBlockSlice = prismic.SharedSlice<
  "get_in_touch_block",
  GetInTouchBlockSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * SubHeading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Highlight → Primary*
 */
export interface HighlightSliceDefaultPrimary {
  /**
   * Heading field in *Highlight → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Highlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Highlight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image (Mobile) field in *Highlight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_image: prismic.ImageField<never>;
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HighlightSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Highlight → Primary*
 */
export interface HighlightSliceReversePrimary {
  /**
   * Heading field in *Highlight → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Body field in *Highlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Highlight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image (Mobile) field in *Highlight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mobile_image: prismic.ImageField<never>;
}

/**
 * Reverse variation for Highlight Slice
 *
 * - **API ID**: `reverse`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceReverse = prismic.SharedSliceVariation<
  "reverse",
  Simplify<HighlightSliceReversePrimary>,
  never
>;

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault | HighlightSliceReverse;

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
  "highlight",
  HighlightSliceVariation
>;

/**
 * Primary content in *Map → Primary*
 */
export interface MapSliceDefaultPrimary {
  /**
   * Coordinates field in *Map → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: map.primary.coordinates
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  coordinates: prismic.GeoPointField;

  /**
   * Marker Label field in *Map → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: map.primary.marker_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  marker_label: prismic.KeyTextField;
}

/**
 * Default variation for Map Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Map*
 */
type MapSliceVariation = MapSliceDefault;

/**
 * Map Shared Slice
 *
 * - **API ID**: `map`
 * - **Description**: Map
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapSlice = prismic.SharedSlice<"map", MapSliceVariation>;

/**
 * Primary content in *OurTeam → Primary*
 */
export interface OurTeamSliceDefaultPrimary {
  /**
   * Heading field in *OurTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Tagline field in *OurTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * Button Label field in *OurTeam → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Navigates To field in *OurTeam → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.primary.button_navigates_to
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_navigates_to: prismic.LinkField;
}

/**
 * Primary content in *OurTeam → Items*
 */
export interface OurTeamSliceDefaultItem {
  /**
   * Icon field in *OurTeam → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Heading field in *OurTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *OurTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for OurTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceDefaultPrimary>,
  Simplify<OurTeamSliceDefaultItem>
>;

/**
 * Slice variation for *OurTeam*
 */
type OurTeamSliceVariation = OurTeamSliceDefault;

/**
 * OurTeam Shared Slice
 *
 * - **API ID**: `our_team`
 * - **Description**: OurTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSlice = prismic.SharedSlice<
  "our_team",
  OurTeamSliceVariation
>;

/**
 * Primary content in *OurValue → Primary*
 */
export interface OurValueSliceDefaultPrimary {
  /**
   * Heading field in *OurValue → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Tagline field in *OurValue → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * Featured Image field in *OurValue → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Featured Heading field in *OurValue → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.primary.featured_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_heading: prismic.RichTextField;

  /**
   * Featured Tagline field in *OurValue → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.primary.featured_tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_tagline: prismic.RichTextField;
}

/**
 * Primary content in *OurValue → Items*
 */
export interface OurValueSliceDefaultItem {
  /**
   * Heading field in *OurValue → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *OurValue → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_value.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for OurValue Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurValueSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurValueSliceDefaultPrimary>,
  Simplify<OurValueSliceDefaultItem>
>;

/**
 * Slice variation for *OurValue*
 */
type OurValueSliceVariation = OurValueSliceDefault;

/**
 * OurValue Shared Slice
 *
 * - **API ID**: `our_value`
 * - **Description**: OurValue
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurValueSlice = prismic.SharedSlice<
  "our_value",
  OurValueSliceVariation
>;

/**
 * Primary content in *Post → Primary*
 */
export interface PostSliceDefaultPrimary {
  /**
   * body field in *Post → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Post → Items*
 */
export interface PostSliceDefaultItem {
  /**
   * related_post field in *Post → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: post.items[].related_post
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  related_post: prismic.ContentRelationshipField<"blog_post">;
}

/**
 * Default variation for Post Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PostSliceDefaultPrimary>,
  Simplify<PostSliceDefaultItem>
>;

/**
 * Slice variation for *Post*
 */
type PostSliceVariation = PostSliceDefault;

/**
 * Post Shared Slice
 *
 * - **API ID**: `post`
 * - **Description**: Post
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PostSlice = prismic.SharedSlice<"post", PostSliceVariation>;

/**
 * Primary content in *Reviews → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
  /**
   * Tagline field in *Reviews → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *Reviews → Items*
 */
export interface ReviewsSliceDefaultItem {
  /**
   * Heading field in *Reviews → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *Reviews → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;

  /**
   * Author Image field in *Reviews → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author Name field in *Reviews → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Tagline field in *Reviews → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.items[].author_tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_tagline: prismic.KeyTextField;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceDefaultPrimary>,
  Simplify<ReviewsSliceDefaultItem>
>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Reviews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsSlice = prismic.SharedSlice<
  "reviews",
  ReviewsSliceVariation
>;

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * testimonial field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;

  /**
   * author_name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_name: prismic.KeyTextField;

  /**
   * author_image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * author_tagline field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].author_tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author_tagline: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *VideoBanner → Primary*
 */
export interface VideoBannerSliceDefaultPrimary {
  /**
   * VideoURL field in *VideoBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_banner.primary.videourl
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videourl: prismic.KeyTextField;

  /**
   * Heading field in *VideoBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *VideoBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_banner.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Mobile VideoURL field in *VideoBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_banner.primary.mobile_videourl
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mobile_videourl: prismic.KeyTextField;
}

/**
 * Default variation for VideoBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBanner*
 */
type VideoBannerSliceVariation = VideoBannerSliceDefault;

/**
 * VideoBanner Shared Slice
 *
 * - **API ID**: `video_banner`
 * - **Description**: VideoBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBannerSlice = prismic.SharedSlice<
  "video_banner",
  VideoBannerSliceVariation
>;

/**
 * Primary content in *WhoWeAre → Primary*
 */
export interface WhoWeAreSliceDefaultPrimary {
  /**
   * Heading field in *WhoWeAre → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_we_are.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Tagline field in *WhoWeAre → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_we_are.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * Contact Phone Number field in *WhoWeAre → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_we_are.primary.contact_phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_phone_number: prismic.KeyTextField;

  /**
   * Featured Image field in *WhoWeAre → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: who_we_are.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Featured Image Lable field in *WhoWeAre → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_we_are.primary.featured_image_lable
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featured_image_lable: prismic.KeyTextField;
}

/**
 * Primary content in *WhoWeAre → Items*
 */
export interface WhoWeAreSliceDefaultItem {
  /**
   * Item field in *WhoWeAre → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: who_we_are.items[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Default variation for WhoWeAre Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhoWeAreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhoWeAreSliceDefaultPrimary>,
  Simplify<WhoWeAreSliceDefaultItem>
>;

/**
 * Slice variation for *WhoWeAre*
 */
type WhoWeAreSliceVariation = WhoWeAreSliceDefault;

/**
 * WhoWeAre Shared Slice
 *
 * - **API ID**: `who_we_are`
 * - **Description**: WhoWeAre
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhoWeAreSlice = prismic.SharedSlice<
  "who_we_are",
  WhoWeAreSliceVariation
>;

/**
 * Primary content in *WhyChooseUs → Primary*
 */
export interface WhyChooseUsSliceDefaultPrimary {
  /**
   * Heading field in *WhyChooseUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Tagline field in *WhyChooseUs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;

  /**
   * Button Label field in *WhyChooseUs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Background Image field in *WhyChooseUs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Button Navigates To field in *WhyChooseUs → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.primary.button_navigates_to
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_navigates_to: prismic.LinkField;
}

/**
 * Primary content in *WhyChooseUs → Items*
 */
export interface WhyChooseUsSliceDefaultItem {
  /**
   * Icon field in *WhyChooseUs → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Heading field in *WhyChooseUs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Tagline field in *WhyChooseUs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.items[].tagline
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tagline: prismic.RichTextField;
}

/**
 * Default variation for WhyChooseUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyChooseUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyChooseUsSliceDefaultPrimary>,
  Simplify<WhyChooseUsSliceDefaultItem>
>;

/**
 * Slice variation for *WhyChooseUs*
 */
type WhyChooseUsSliceVariation = WhyChooseUsSliceDefault;

/**
 * WhyChooseUs Shared Slice
 *
 * - **API ID**: `why_choose_us`
 * - **Description**: WhyChooseUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyChooseUsSlice = prismic.SharedSlice<
  "why_choose_us",
  WhyChooseUsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      LocationDocument,
      LocationDocumentData,
      LocationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataDropdownItemsItem,
      ServicePageDocument,
      ServicePageDocumentData,
      ServicePageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSlicesSlice,
      SettingsDocumentDataCtaItem,
      SettingsDocumentDataMenuItem,
      SettingsDocumentDataSocialLinksItem,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceTextBottomPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BannerSliceTextBottom,
      BlogGridSlice,
      BlogGridSliceDefaultPrimary,
      BlogGridSliceVariation,
      BlogGridSliceDefault,
      BlogPreviewSlice,
      BlogPreviewSliceDefaultPrimary,
      BlogPreviewSliceDefaultItem,
      BlogPreviewSliceVariation,
      BlogPreviewSliceDefault,
      BodySlice,
      BodySliceDefaultPrimary,
      BodySliceVariation,
      BodySliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContentGridSlice,
      ContentGridSliceDefaultPrimary,
      ContentGridSliceDefaultItem,
      ContentGridSliceVariation,
      ContentGridSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceDefaultItem,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      GetInTouchBlockSlice,
      GetInTouchBlockSliceVariation,
      GetInTouchBlockSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HighlightSlice,
      HighlightSliceDefaultPrimary,
      HighlightSliceReversePrimary,
      HighlightSliceVariation,
      HighlightSliceDefault,
      HighlightSliceReverse,
      MapSlice,
      MapSliceDefaultPrimary,
      MapSliceVariation,
      MapSliceDefault,
      OurTeamSlice,
      OurTeamSliceDefaultPrimary,
      OurTeamSliceDefaultItem,
      OurTeamSliceVariation,
      OurTeamSliceDefault,
      OurValueSlice,
      OurValueSliceDefaultPrimary,
      OurValueSliceDefaultItem,
      OurValueSliceVariation,
      OurValueSliceDefault,
      PostSlice,
      PostSliceDefaultPrimary,
      PostSliceDefaultItem,
      PostSliceVariation,
      PostSliceDefault,
      ReviewsSlice,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceDefaultItem,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      VideoBannerSlice,
      VideoBannerSliceDefaultPrimary,
      VideoBannerSliceVariation,
      VideoBannerSliceDefault,
      WhoWeAreSlice,
      WhoWeAreSliceDefaultPrimary,
      WhoWeAreSliceDefaultItem,
      WhoWeAreSliceVariation,
      WhoWeAreSliceDefault,
      WhyChooseUsSlice,
      WhyChooseUsSliceDefaultPrimary,
      WhyChooseUsSliceDefaultItem,
      WhyChooseUsSliceVariation,
      WhyChooseUsSliceDefault,
    };
  }
}
