// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  blog_grid: dynamic(() => import("./BlogGrid")),
  blog_preview: dynamic(() => import("./BlogPreview")),
  body: dynamic(() => import("./Body")),
  call_to_action: dynamic(() => import("./CallToAction")),
  commercial_services: dynamic(() => import("./CommercialServices")),
  content_grid: dynamic(() => import("./ContentGrid")),
  faq_section: dynamic(() => import("./FaqSection")),
  get_in_touch_block: dynamic(() => import("./GetInTouchBlock")),
  hero: dynamic(() => import("./Hero")),
  highlight: dynamic(() => import("./Highlight")),
  keys_gallery: dynamic(() => import("./KeysGallery")),
  locations: dynamic(() => import("./Locations")),
  map: dynamic(() => import("./Map")),
  our_services: dynamic(() => import("./OurServices")),
  our_team: dynamic(() => import("./OurTeam")),
  our_value: dynamic(() => import("./OurValue")),
  post: dynamic(() => import("./Post")),
  reviews: dynamic(() => import("./Reviews")),
  testimonials: dynamic(() => import("./Testimonials")),
  video_banner: dynamic(() => import("./VideoBanner")),
  who_we_are: dynamic(() => import("./WhoWeAre")),
  why_choose_us: dynamic(() => import("./WhyChooseUs")),
};
